### ISSUE TITLE
Update the list of Recent Files Tab after renaming a file

### ISSUE THREAD

**Issue by icr1001** [tgrosinger/recent-files-obsidian#1]
**Issue**: It does not update the file name at the **Recent Files tab** after renaming a file.

Other suggestions:
- Have the option to set the number of recent files in the **Recent Files Tab**.
- Have the option to clean the **Recent Files**‘ list.

Thanks for this plugin, it is amazing!

**Comment by tgrosinger** [comment]
Yeah, I have not found a good way to detect what a file is renamed to. Hopefully I can find that, but in the mean time you can work around this by just clicking on the invalid file in the list. It should disappear 🙂 

Thanks for the other suggestions. I created new issues for them (#2 & #3)

**Comment by luckman212** [comment]
I posted this to the Forum: https://forum.obsidian.md/t/api-callback-for-file-rename-event/11395

**Comment by tgrosinger** [comment]
A suggestion from the forum:

> I don’t know how officially supported this is, but `app.vault.on("rename", function(file, oldname) {})` will notify you of renames done from Obsidian’s file manager or pane title fields. It does not notify about renames initiated from outside of Obsidian.

**Comment by pjeby** [comment]
You probably also want `app.vault.on("delete", function(file){})` to remove deleted files.  ;-)

**Comment by tgrosinger** [comment]
Also a great suggestion. I will put that in a separate issue.
