### ISSUE TITLE
Use the "clock" icon starting in 0.11.4

### ISSUE THREAD

**Issue by ericaxu** [tgrosinger/recent-files-obsidian#10]
Hi Tony,

I'm really enjoying the plugin!

We've added a native icon for "clock", and I wonder if you could try using that and see if it looks more consistent with the other icons? Thanks!

(Of course wait until 0.11.4 goes public to release it, so that people's icons don't become broken 😅 )

**Comment by tgrosinger** [comment]
The clock Icon seems to be a checkmark? Is it just called "clock"?

<img width="727" alt="Screen Shot 2021-02-28 at 8 20 05 AM" src="https://user-images.githubusercontent.com/597386/109425627-ff00c900-799d-11eb-8d97-e6b128b7dbe8.png">

**Comment by ericaxu** [comment]
Sorry, it was my bad. Pasted the wrong thing.

Could you try again when 0.11.5 is out? This patch version should be out soon.

**Comment by ericaxu** [comment]
Does 0.11.6 (insider) fix it?

**Comment by tgrosinger** [comment]
Yes it does. Thank you.
