### ISSUE TITLE
[BUG] Files with any tags are omitted

### ISSUE THREAD

**Issue by blumenschwein** [tgrosinger/recent-files-obsidian#101]
Dear developer,

in the latest version there is a problem with files containing tags in the frontmatter

* Version: 1.7.0
* Problem: any file with any tags are omitted, only files without tags are displayed
* Settings: default setting, nothing is  changed:
![image](https://github.com/user-attachments/assets/14fedfbc-9e3f-4aab-8aed-8731df3b4da5)
* Desired behavior: only files with specific tags are omitted
* Platforms with this problem: Ubuntu 22, Windows 11, Android

Also, there is a TypeError in the plugin, I' m not sure if this error is related to the problem above.
![image](https://github.com/user-attachments/assets/76e01e6e-c4a9-4f2e-b705-b1de4463db67)

**Comment by tgrosinger** [comment]
@zayKenyon want to take a look at this, or would you prefer I check it out?

**Comment by zayKenyon** [comment]
@blumenschwein Is there a file that you would be okay sharing that I could try the plugin with? The files I'm creating don't have the same effect unfortunately 🙁. I believe you may be onto something, in the Obsidian Inspect Element where can I find that function? 😅

@tgrosinger I took a quick look and I've come up short. This might be above me, sorry for introducing problems. The only platform I can reasonably test this on is Windows, and I'm not able to reproduce the reported effect. I've got a file here with a tag, the setting is disabled yet the file shows [Attached]. 

![image](https://github.com/user-attachments/assets/585a0ad8-8202-47d0-8440-fbe7af12d625)

**Comment by tgrosinger** [comment]
Thanks for taking a look @zayKenyon, and no worries. I'll take a look in the next few days and report back :)
