### ISSUE TITLE
[enhancement] fuzzy/incremental search

### ISSUE THREAD

**Issue by attilaszkrs** [tgrosinger/recent-files-obsidian#104]
Could we have a functionality to filter items by a simple fuzzy search? 

Ideally, a search bar could be implemented at the top of the vertical tab. As the user types, the list of note titles would be filtered in real-time to display only those containing the entered text. This would greatly enhance navigation and discoverability, especially when dealing with a large number of recently active notes.

**Comment by zayKenyon** [comment]
Personally, if I needed to search for the note, I would reach for the Quick Switcher instead of navigating through the Explorer search bar. For that reason I wouldn't agree with its implementation but I wonder if I'm in the minority.

**Comment by tgrosinger** [comment]
Agreed, let's keep the search functionality to the Search view and the Quick Switcher.
