### ISSUE TITLE
Omitted frontmatter tags: Support for nested tags

### ISSUE THREAD

**Issue by avirosso** [tgrosinger/recent-files-obsidian#108]
Thanks for this great plugin!

The option to omit certain frontmatter tags is great - but unfortunately, nested tags are not yet supported

Like many others, I have a deep hierarchy of nested tags like this:

Note1:
```
tags:
  - archive/a/b/c
```

Note2

```
tags:
  - archive/m/n/o
```

Note 3

```
tags:
  - archive/x/y/z
```

There must be a way to omit all notes (recent files) with the 'archive' tag (with any sub-tags)

Thanks in advance!

**Comment by tgrosinger** [comment]
Right now tags are exact match only. This could be added by making tags support regex matching, like we have for file paths. @zayKenyon want to take this one on?

**Comment by zayKenyon** [comment]
Thanks for the suggestion, I'll see what I can do.

The description of the Frontmatter tags setting says 'Frontmatter tags patterns' so it would make double sense if it had regex support.

**Comment by zayKenyon** [comment]
@avirosso I've submitted a PR which aims to introduce this functionality, if you get a chance I'd appreciate it if you could let me know if it works for you!

**Comment by avirosso** [comment]
Sorry, I'm not a developer - I can only test a new official version of the plugin.

**Comment by zayKenyon** [comment]
> Sorry, I'm not a developer - I can only test a new official version of the plugin.

Fair enough, no apologies necessary!
