### ISSUE TITLE
An option to put it on the right panel (mobile)

### ISSUE THREAD

**Issue by Glormond** [tgrosinger/recent-files-obsidian#109]
Hi there. In mobile version (iOS), the "recent files" appears on the right panel, together with Files, Bookmarks etc. 
I mostly use Files all the time, as well as Recent Files, so constantly switching back and forth seems a bit uncomfortable to me. 
Is there a way to put it on the right panel, where Calendar, Backlinks etc.? 

Thanks in advance!

![IMG_2653](https://github.com/user-attachments/assets/c57d2cf3-769a-4459-b180-34fc810769fc)
![IMG_2654](https://github.com/user-attachments/assets/8066fc58-44fe-47a9-ac9c-320045d7beda)

**Comment by tgrosinger** [comment]
Hello,
Generally Obsidian encourages plugin views that are specific to the open note to be on the right, and views which are general to the whole vault to be on the left. It's not a hard-fast rule, but a guideline.

I understand it would be preferable to make this configurable, but with the options open to us right now, I think it is best to keep the Recent Files view on the left.
