### ISSUE TITLE
Middle click to open in new pane

### ISSUE THREAD

**Issue by davecan** [tgrosinger/recent-files-obsidian#11]
Can the plugin be configured to recognize a click on the mouse wheel as equivalent to Cmd-click i.e. open the note in a new pane?

Currently the backlinks pane works this way as does the file navigator – clicking a note title opens the note in the current pane but middle-clicking is the same as Cmd-clicking.

**Comment by tgrosinger** [comment]
To maintain consistency with the built-in file viewer, this functionality should be associated with ctrl+click instead of middle click.
