### ISSUE TITLE
ability for note title to wrap into multiple lines 

### ISSUE THREAD

**Issue by rickyribeiroo** [tgrosinger/recent-files-obsidian#112]
Dear Tony @tgrosinger,

I would like to request the ability for the note title to wrap into multiple lines so I can see all the note title content in the UI. 
Most of my notes have long titles and since "Recent Files" is on my sidebar, what ends up happening is the note title gets truncated. Here's a screenshot to illustrate that:

![image](https://github.com/user-attachments/assets/a4acf59b-0216-41ea-82c7-80f3a912c460)

If you're available and willing, I would very much appreciate this feature. As an example, the native search feature of Obsidian already wraps the note titles: 
![image](https://github.com/user-attachments/assets/8b8ae9b9-69a6-40a7-8989-bf8a84b06e34)

Thank you very much

**Comment by tgrosinger** [comment]
Hi @rickyribeiroo, thanks for the feature request. The Recent Files view is styled to match as closely with the default "Files" view as possible, not the Search view. That is why it truncates the name of longer files.

You could reduce the amount of truncating by making your side bar a little wider though. Click on the vertical edge of the sidebar and drag towards the center of the app to increase its size. You can also hide and show the sidebar with a hotkey, so if you made it very wide you could hide it except when it is needed.
