### ISSUE TITLE
Support inserting a file link to an active note by dragging a link from the recent files list

### ISSUE THREAD

**Issue by wenlzhang** [tgrosinger/recent-files-obsidian#12]
Is it possible to support inserting a file link to an active note by dragging a link from the recent files list? For instance, one can insert a file link by dragging from the starred files list, which is a native Obsidian feature.

**Comment by luckman212** [comment]
I was looking into this and it seems that the native file list has a `draggable="true"` property attached to its `"nav-file-title"` div elements. Simply adding this to the Recent Files items (via dev tools) allows them to become draggable.

Unfortunately dropping them onto the editor does not do anything. There's some missing plumbing, but it seems like something that should be supportable with just a few lines of code if the API allows it. There's also a `"data-path="whatever.md"` property that could be relevant.

![image](https://user-images.githubusercontent.com/1992842/115031969-c60dac80-9e96-11eb-8f4b-8bc33a84ef64.png)

**Comment by tgrosinger** [comment]
Nice, good find @luckman212. Looks like Liam has the answer for the second half of it: https://github.com/liamcain/obsidian-calendar-ui/blob/e86d31af2fa203aba35167ba7a5e7e17e299ebc8/src/fileStore.ts#L148

**Comment by luckman212** [comment]
Amazing @tgrosinger ! I tried sniffing around in the source of a few file-related plugins to see if someone had figured this out but I came up empty handed. I should have known @liamcain would have the answer.
