### ISSUE TITLE
Add hover preview over file titles

### ISSUE THREAD

**Issue by classicrob** [tgrosinger/recent-files-obsidian#17]
Hi! I use a lot of notes with ZK prefixer so the titles aren't always the most descriptive. Being able to hover preview would be really helpful!

**Comment by tgrosinger** [comment]
Seems to be a duplicate of #18.

**Comment by classicrob** [comment]
Not a duplicate - the other request is that context is immediately visible as I scroll through it. This is asking for the ability to hover preview and see more context if necessary.

**Comment by tgrosinger** [comment]
Ah, I misread. Thanks.

**Comment by tgrosinger** [comment]
See comment in https://github.com/tgrosinger/recent-files-obsidian/issues/18#issuecomment-822007664
