### ISSUE TITLE
View little previews of the first few non-YAML lines of pages, as though it were a search for all of your notes sorted by recency

### ISSUE THREAD

**Issue by classicrob** [tgrosinger/recent-files-obsidian#18]
Hi! I use a lot of notes with ZK prefixer so the titles aren't always the most descriptive. Being able to see a little preview of the first few lines of the note would be really helpful! See how it works in Bear for reference, but ideally it would add a few more lines of the note: 
![image](https://user-images.githubusercontent.com/46608303/115148695-f764b480-a01d-11eb-8d44-f031207f9754.png)

**Comment by tgrosinger** [comment]
This plugin is meant to mirror the look and feel of the native file explorer as closely as possible. I will see if I can get the core Page Preview plugin to work in the Recent Files view.

**Comment by tgrosinger** [comment]
From Licat:

```
Workspace.trigger('hover-link', {
    event: MouseEvent;
    source: string;
    hoverParent: HoverParent;
    targetEl: HTMLElement | null;
    linktext: string;
    sourcePath?: string;
    state?: any;
})
```

```
Workspace.registerHoverLinkSource('source-id', {
    display: 'Source Name',
    defaultMod: true/false,
});
Workspace.unregisterHoverLinkSource('source-id');
```

From Liam: https://github.com/liamcain/obsidian-calendar-plugin/blob/7d2aebda7f4a280bedc6da6d25f4da611d1625ef/src/view.ts#L127

**Comment by luckman212** [comment]
@tgrosinger Cool find. Can I request that this feature be optional though (if you implement it)? I'm not a fan of hover previews - for me they are too distracting.

**Comment by tgrosinger** [comment]
Yeah, I definitely agree. I am hopeful to make it work if the preview page plugin is turned on, and not otherwise. That way no additional settings are necessary.

**Comment by tgrosinger** [comment]
I understand now that this is a request to add context lines to the file listing, not hover preview. I do not think context lines fit in this plugin, since as mentioned previously, this is trying to look as similar to the core File Explorer as possible. I will however investigate the hover functionality in #18.
