### ISSUE TITLE
Hotkey for Recent Files

### ISSUE THREAD

**Issue by pivovarov1** [tgrosinger/recent-files-obsidian#24]
Hey, 
It would be nice to add hotkey, for example: 
`Ctrl + Shift + T` (like in browser)

So that when you click on it:
1. the recent file opens. 
2. If it is already open , you can go ahead and open the next file from the "Recent Files" list.

Thanks!

**Comment by iamprem** [comment]
This is a much needed feature because how easy it will make switching between two files often.

**Comment by marblewraith** [comment]
There are already native Obsidian commands / hotkeys that do this.

- Navigate back: `ctrl + alt + ←`
- Navigate forward: `ctrl + alt + →`

This issue should probably be closed.

**Comment by jerrygreen** [comment]
`ctrl + alt + ←` `ctrl + alt + →` doesn't work exactly like recent files

- After you release `ctrl + alt + ←`, now your most recent file is this one you just had showing, right?
- Therefore, pressing `ctrl + alt + ←` again should navigate you back to the file you just was at, right?

So, it's kinda like the systrem's `alt + tab`, right? That's what I expected at least.

_But instead_, with Obsidian's logic, it continues to cycle through the past files.

I.e., releasing `ctrl + alt` doesn't change the history of recent files, so it's different than `alt + tab` logic.

It would be cool if this plugin provided hotkey that resemble more of `alt + tab` but for Obsidian notes.

It should rewrite recent history after buttons are released.

**Comment by tgrosinger** [comment]
The forward and backward buttons in Obsidian are more like the same buttons in a web browser instead of being like alt+tab.

Obsidian does have a list of recent files in the quick switcher, which can be bound to a hotkey.

You can bind a hotkey to open the recent files sidebar view. I think that is the only hotkey needed in this plugin.
