### ISSUE TITLE
FR: please, add 'recently modified' mode

### ISSUE THREAD

**Issue by VKondakoff** [tgrosinger/recent-files-obsidian#25]
Hello!

As we are talking of recent files, I'm mostly interested in a flat list of, say, 10 recently modified notes instead of the list of recently opened notes (because the latter is available in Quick switcher).
Can you please add a 'recently modified' mode to 'recent-files-obsidian'?

Thanks!

**Comment by cristianvasquez** [comment]
Or alternatively, add a different color (css class) to the elements what where :

1. Seen the last 24 hours
2. Modified the last 24 hours

Then one could have a better clue of what one is working on

**Comment by wedgiebee** [comment]
I agree with original post, it would be awesome to have an option to order by "recently modified" instead of "recently opened!"

**Comment by hmijail** [comment]
Came looking for that same option!

**Comment by tgrosinger** [comment]
The built-in file viewer allows you to change the sort order and list files in order of modified time. I don't think that feature needs to be added to this plugin too.

![image](https://github.com/tgrosinger/recent-files-obsidian/assets/597386/10994f73-63e3-4b3b-9fbd-bd8c61e748c2)
