### ISSUE TITLE
Calendar of created/modified events?

### ISSUE THREAD

**Issue by haosmark** [tgrosinger/recent-files-obsidian#26]
Is this plugin still being developed? Would be pretty amazing to add a calendar feature which would allow viewing created/modified files on specific days / weeks / months.

**Comment by tgrosinger** [comment]
It's not really still being developed, as it meets my needs and has the features I set out to create originally.

Thank you for the feature suggestion. I think that the calendar feature you describe is outside of the scope of this plugin.
