### ISSUE TITLE
Could there be a command to show the "Recent Files" pane?

### ISSUE THREAD

**Issue by claremacrae** [tgrosinger/recent-files-obsidian#27]
Hello, I'm finding this really useful - and on ipad and iPhone I would like to make it easier to open by adding a button on the Left Ribbon to show the "Recent Files" pane.

This would be easy to do with Customizable Sidebar if there was a command to open the pane...

If it's something you feel is doable, but don't have time, I would be happy to try making a PR to add the feature...

**Comment by omnosti** [comment]
I was going to make a feature request with a similar title, but my idea was for a command palette command for showing the recent files pane. There are command palette commands for showing other side panes, like the tag pane, starred pane, backlinks pane, etc., so it would make sense for the recent files pane to have an equivalent command, and this addition would also open up the option to have a hotkey for showing the pane.

**Comment by uwe999** [comment]
I would like that feature as well. You could then set a hotkey like CTRL+R to bring up recent files.
In addition it would be helpful to navigate the recent files list with cursor up/down, then hit enter to open file

**Comment by davebhc71** [comment]
Using Mobile on iPad having a gif in the left most Sidebar to activate this would be great!

**Comment by miluoshi** [comment]
I've implemented it in #37. Waiting for a review 🙏
