### ISSUE TITLE
Add more commands to the context menu

### ISSUE THREAD

**Issue by chrisgrieser** [tgrosinger/recent-files-obsidian#28]
This Plugin is great, thanks for it!
I am thinking about ditching the file explorer by using this plugin and the quick switcher. However, there are some minor things from the file explorer I am missing, namely that this plugin has less options in the context menu than the file explorer. More specifically, I am missing:
- delete file
- make copy of file
- rename file
- open in new pane

**Comment by m-radzikowski** [comment]
I second this. Open in new pane is something I personally miss the most.

**Comment by therden** [comment]
Casting another vote in favor of adding "Open in new pane" to right-click context menu.

Thank you for sharing this plugin!

**Comment by cptvincer** [comment]
I cam here just to request that (and open in new tab too!!)

**Comment by lxq1** [comment]
I wish I could have the right-click menu  （ open in new tab ）

**Comment by tgrosinger** [comment]
Yeah, I don't think we should try to add every feature that the file explorer has. But I will throw out that ctrl+click will open in a new tab, and ctrl+alt+click will open in a new pane.
