### ISSUE TITLE
Hotkeys for copying links of recent x files to clipboard

### ISSUE THREAD

**Issue by wenlzhang** [tgrosinger/recent-files-obsidian#29]
It would be great if one can copy files links of recent x files to clipboard, then one can quickly insert these recently modified files to other desired notes. Regarding how many links to copy, one can set the value for x in the configuration pane.

The following issue may be related: https://github.com/tgrosinger/recent-files-obsidian/issues/24

**Comment by zayKenyon** [comment]
Does [this ](https://github.com/tgrosinger/recent-files-obsidian/issues/24#issuecomment-2383507499)comment close this?
