### ISSUE TITLE
Reduce extra space to left of file list

### ISSUE THREAD

**Issue by zhl111** [tgrosinger/recent-files-obsidian#30]
![image](https://user-images.githubusercontent.com/29135984/144348051-bdf8b2c2-1294-4f49-a3e7-16f67ecb6eba.png)

**Comment by tgrosinger** [comment]
Hello,
I'm not really sure what the photo is showing. Can you please describe the bug you are encountering?

**Comment by zhl111** [comment]
Actually, I want the file name of the recent files to show more words
![image](https://user-images.githubusercontent.com/29135984/144358711-7af076d1-71f4-4425-a944-aea6d5551a9b.png)
![image](https://user-images.githubusercontent.com/29135984/144359161-2874a11c-5ba3-4cc2-a75c-9273b80b42ad.png)

**Comment by tgrosinger** [comment]
I understand now and updated the title accordingly. I'll take a look into this.
Thanks

**Comment by zayKenyon** [comment]
This is in-line with the spacing of the standard file explorer, I don't think this is a RecentFiles issue.

The image tries to demonstrate that with-or-without a folder, the spacing consistently has a left-padding.
![image](https://github.com/user-attachments/assets/bc373b64-3be5-4a67-8890-d973a8701ee5)
