### ISSUE TITLE
Add Recent File Icon Button on iPad

### ISSUE THREAD

**Issue by pixelinkmedia** [tgrosinger/recent-files-obsidian#36]
Hi, thanks for this plugin.

On the Obs desktop app there is a Recent File icon button on the top of navigation pane next to the "starred" icon button.

However, on the iPad Pro (Obs ver 1.05) there is NO icon at all (just File Explorer, Folder, Sort button).
The only to view Recent files is I have to go backwards by clicking the "File Explore" text button to see the Recent File icon button.

Could it be possible to put an icon button on the navigation pane right next to the Sort icon button?

This would make it much quicker and convenient to get to the most Recent Files pane.

Thanks

**Comment by pixelinkmedia** [comment]
Sorry, thought the last post I did didn't post, so I created this one again.

**Comment by davebhc71** [comment]
There ar a couple versions of this FR. Are any of them under consideration for Mobile (especially iPad)? 🙏

**Comment by davebhc71** [comment]
Oops! Failed to install on iPad Air.😳
