### ISSUE TITLE
Since recent versions of Obisidian (eg 0.15.2) clicking file from Recent List does not update Outline

### ISSUE THREAD

**Issue by luckman212** [tgrosinger/recent-files-obsidian#41]
Not sure where to begin debugging this but:

When I open a file from RecentFileList, the Outline on the sidebar does not refresh/update.

Clicking the same file from the native file tree works.

I guess there have been some breaking API changes...

**Comment by tgrosinger** [comment]
I'm not sure what you mean by the outline on the sidebar. Do you mean the list of recent files does not update?
I'm not able to reproduce that issue, but let me know if I am misunderstanding.

**Comment by Alpengreis** [comment]
I also can't reprocude that or I also misunderstood it.

Would be good if @luckman212 could explain the issue.

**Comment by luckman212** [comment]
Not sure what the issue was, but I re-tested using the latest versions of everything and can't reproduce. Thanks for checking guys, closing.

**Comment by AMGMNPLK** [comment]
I get this error frequently. I don't know how to reproduce it.
