### ISSUE TITLE
Open in new tab

### ISSUE THREAD

**Issue by menagerie198** [tgrosinger/recent-files-obsidian#44]
Since Obs 0.16.0, when I click to open a file from 'Recent Files', the file opens the file/tab in a split (vertical, to the right) window. Could we have this action open the file in a new tab?

**Comment by nbarman2022** [comment]
I have this same issue and request.

**Comment by Peingxious** [comment]
Now Obs 1.0.0 ,Could we have this action open the file in a new tab?

**Comment by lewisjiang** [comment]
I've implemented the function in #47 and it is now waiting for review.
