### ISSUE TITLE
1.3.4 broke file list style 

### ISSUE THREAD

**Issue by pcuellar** [tgrosinger/recent-files-obsidian#48]
Upon updating to 1.3.4 using MInimal theme, the styling of the file list is broken. See screenshots 1.3.3 and 1.3.4 below

**1.3.3**
<img width="208" alt="Screenshot 2022-11-28 at 5 55 54 PM" src="https://user-images.githubusercontent.com/20482146/204197226-363fe827-05b7-4c3b-b979-b24848987b76.png">

**1.3.4**
<img width="222" alt="Screenshot 2022-11-28 at 5 54 32 PM" src="https://user-images.githubusercontent.com/20482146/204197194-000c0136-93db-47b0-82d3-77702695f600.png">

**Comment by tgrosinger** [comment]
Yeah, it looks like they are a little different even in the stock theme. I'll take another pass at that.

**Comment by tgrosinger** [comment]
Fixed in 1.3.5
