### ISSUE TITLE
switching vaults, same list

### ISSUE THREAD

**Issue by andyczerwonka** [tgrosinger/recent-files-obsidian#49]
The recent files are not updated when I switch vaults, vaults where I share configuration. Maybe my setup is wrong? I would think recent files is setup on a per-vault basis (vault data), and not stored in the configuration.

**Comment by tgrosinger** [comment]
The recent files list is stored in the plugin data, which is stored in the `.obsidian` directory in your vault. In my experience different vaults have a different `.obsidian` directory. I have not encountered them sharing lists of files.

Can you provide more information about your directory structure?

**Comment by andyczerwonka** [comment]
I've seen users share their configuration, e.g. which plugins do I have installed, what appearance, hotkeys, etc. None of that is a function of the data, i.e. what documents I have stored in my vault. There are two ways I've seen people share:

1. The `.obsidian` directory is a git sub-module, pulled into two separate root repositories, or,
2. It's a symlink to a location elsewhere.

I'm not aware of other plugins that depend of actual vault data, but I may be mistaken. At least I'm not using them. Here's the list I'm using now. 

![image](https://user-images.githubusercontent.com/138898/204354937-ba0a6f57-5433-4e16-b07f-aebe6c541a29.png)

**Comment by tgrosinger** [comment]
@andyczerwonka, if you're sharing the `.obsidian` directory between vaults then this plugin will not work properly for you. Perhaps you can setup the `.gitignore` to leave out the recent-files plugin.

I'm going to go ahead and close this issue since it does not sound like the plugin is behaving unexpectedly.

**Comment by andyczerwonka** [comment]
@tgrosinger All good, I removed it altogether. I knew it was behaving as designed, I created the ticket suggesting an alternative design, but understand that I may represent a minority workflow. I think this feature is on the roadmap, so the native implementation might behave differently.
