### ISSUE TITLE
Exclude file names

### ISSUE THREAD

**Issue by luckman212** [tgrosinger/recent-files-obsidian#5]
@tgrosinger wonderful plugin!

Would you consider adding a field for file _names_ to omit, similar to `omittedPaths` (or combined with)? I'd like to prevent notes such as "temp*" and "Untitled*" from showing up in my recent list.

**Comment by tgrosinger** [comment]
Hi Luke, thank you 🙂 

The omittedPaths field will operate on the whole note name. So you can put "temp" or "Untitled" in there and it should work.

Let me know if that works for you.

**Comment by luckman212** [comment]
Well whaddya know. That does indeed work!  Just bought you a few ☕ 's

**Comment by tgrosinger** [comment]
Thank you so much!

**Comment by luckman212** [comment]
@tgrosinger Sorry to ask again. But for some reason today it's not working. I've tried adding `Untitled`, `*/Untitled*` and `*Untitled*` as pathspecs but none of them seem to be taking effect.

![image](https://user-images.githubusercontent.com/1992842/104470189-7235b380-5587-11eb-82b7-0030fc866edb.png)

Obsidian 0.10.8 - here is my current setting:
![image](https://user-images.githubusercontent.com/1992842/104470543-d22c5a00-5587-11eb-9120-6d38b7d770af.png)

**Comment by tgrosinger** [comment]
It currently does not have any wildcard support, just a plain text path prefix check. Is that "Untitled" note in a directory, or in the root of the vault?

**Comment by luckman212** [comment]
It's just at the root: /

I tried without the globs (`"Untitled"`) but that's not working either. Tried also with `Pasted image` to have it omit those but again, can't seem to get it to work. Is it a bug in 0.10.8 maybe? I think I was on 0.10.7 when I initially had success with this.

**Comment by tgrosinger** [comment]
Hmm, I am not able to reproduce this. I am running Obsidian 0.10.8 and Recent Files 0.0.5

I put "Untitled" in the omitted paths with nothing else in there (no trailing space or newline) and it does ignore the file.

Are you having it not omit anything? Or are there some patterns that work and others which do not?

**Comment by luckman212** [comment]
This is nuts. I swear I'm not crazy, but you're right - it's working again now. `¯\_(ツ)_/¯`

As for `Pasted image` that still doesn't work, but putting `/attach` prevents anything from my attachments dir from being added, which is good enough.

**Comment by tgrosinger** [comment]
Haha, no worries. Very strange!

Can you tell me more about `Pasted image`? Is that a note name? Is it in a folder? The omission check right now is extremely basic, so something in a folder would need to include the folder and the note name to be omitted. Maybe I should change that?

**Comment by luckman212** [comment]
When I paste (⌘V) an image into Obsidian, it gets automatically named "Pasted image XXXXXXX". Can't see anywhere to control this. I wanted to avoid those files being added to the recent list, so I tried putting that into the omitted paths, but for some reason it's ignored. Adding the entire `/attach` dir does work however.

![image](https://user-images.githubusercontent.com/1992842/104778509-73174280-574b-11eb-8214-19d1a4d4ccbc.png)

**Comment by tgrosinger** [comment]
For some reason I am having a very hard time reproducing this! I tried pasting an image, and got the file you describe. I added "Pasted" to my ignored files list and the line disappeared from my recent files list :-/

Sorry this is proving so difficult! I'm running out of ideas.

**Comment by luckman212** [comment]
That's odd (thank you for trying!)

Are you on Windows, Mac or Linux? I'm wondering if this is a platform-specific edge case.

**Comment by tgrosinger** [comment]
I'm testing it out on Windows.

**Comment by luckman212** [comment]
@tgrosinger Hmm so maybe it's just a macOS thing. In any case, with the new goodies you added (esp. handling file renames) the exclusion list has become less of an issue. It's working well enough now, thank you! (closing)

**Comment by fanghuaqi** [comment]
Dear  @luckman212 , is there a way to support glob pattern to ignore certain files or folders? Thanks for any input.

If not, could there be a feature request for it? if possible I can open another issue.

**Comment by tgrosinger** [comment]
It does not currently support that, however it will match anything following what you input. For example `daily/` will match `daily/2021-04-14`.

You are welcome to open another issue for adding wildcards if that does not meet what you are looking for.

**Comment by fanghuaqi** [comment]
> It does not currently support that, however it will match anything following what you input. For example `daily/` will match `daily/2021-04-14`.
> 
> You are welcome to open another issue for adding wildcards if that does not meet what you are looking for.

Thank you for your reply, I just opened a new issue to track it if you have time to implement it in future.

https://github.com/tgrosinger/recent-files-obsidian/issues/14

**Comment by luckman212** [comment]
@fanghuaqi see #15 - you can test now if you want

download [my fork](https://github.com/luckman212/recent-files-obsidian/archive/refs/heads/add-regex-matching.zip)
cd into the directory
build with `npm i && npm run build` 
copy over `main.js` to your `(vault)/.obsidian/plugins/recent-files-obsidian` dir.
