### ISSUE TITLE
Middle-click, and Right click menu to open in new tab or pane

### ISSUE THREAD

**Issue by diverged** [tgrosinger/recent-files-obsidian#50]
Clicking a note in the Recent Files list does not open the note in a new tab.

From the settings panel: "Open note in: Open the click recent file record in a new tab, split, or window (only works on the desktop app)"

However, clicking a note in the recent files list instead opens the note in place of the currently focused note, and not in a new tab as described.

This wouldn't be a big if it wasn't for the fact that Middle click and Right click are not registered within the Recent Files list.  But as it stands, Right and Middle click are nonfunctional in the Recent Files list, so this is definitely a bug that seemed worth reporting.

Otherwise, thank you for the simple and useful plugin!  I'd offer to help troubleshoot but I am utterly unfamiliar with the Obsidian API (for now).

**Comment by chrisweis** [comment]
Workaround to open in a new tab: Hold CTRL and click the item

**Comment by greatwaldini** [comment]
> Workaround to open in a new tab: Hold CTRL and click the item

Thank you!  I gave that a try, and while that does open a right-click drop down, it does not include the option to open in a new tab.  It only has the option to open in a new window.

The workaround which I've been using to good effect, however, is to simply drag and drop the file into a new tab.  Works plenty well enough to make this bug non-urgent!

**Comment by lxq1** [comment]
I wish I could have the right-click menu （ open in new tab ）

**Comment by brump** [comment]
> > Workaround to open in a new tab: Hold CTRL and click the item
> 
> Thank you! I gave that a try, and while that does open a right-click drop down, it does not include the option to open in a new tab. It only has the option to open in a new window. (This is in a MacOS version of the Obsidian app for context)

On macOS, you generally need to use Cmd instead of Ctrl for Obsidian-related keyboard shortcuts. A Ctrl-click, as you have already discovered, is the same as a right-click on macOS (this stems back to the time when Apple only sold 1-button mice).

**Comment by tgrosinger** [comment]
This will be added in the next release.
