### ISSUE TITLE
Link-URL problem with AnuPpuccin-Theme

### ISSUE THREAD

**Issue by abil76** [tgrosinger/recent-files-obsidian#56]
If you use the Obsidian Theme "AnuPpuccin", you can only open the recent files if you click exactly on the link text. A few millimeters to the right of the text, the left link is not recognized. Solution to the problem: go to the plugin style "Settings/AnuPpuccin/Workspace/File Browser/Fale lable alignment" and set it on  "right".

**Comment by tgrosinger** [comment]
I am unable to provide support for non-default themes. In the default theme you can click anywhere on the row for the filename.
