### ISSUE TITLE
Items do not change color when hovering the mouse over them in the latest Obsidian

### ISSUE THREAD

**Issue by iiz00** [tgrosinger/recent-files-obsidian#57]
Due to changes in Obsidian's DOM structure, in Obsidian v1.2.x, items no longer change color when hovering the mouse over each item in Recent Files, making it a bit difficult to see.
On the user side, the color changes again by adding a snippet like below:
```
.recent-files-title:hover {
    background-color: var(--nav-item-background-hover);
    color:var(--nav-item-color-hover);
}
```

**Comment by tgrosinger** [comment]
I updated the classes on the nodes for Obsidian 1.3 and it seems to be working now. Let me know if you are still having trouble.
