### ISSUE TITLE
Obsidian 1.3 breaks list styling

### ISSUE THREAD

**Issue by czottmann** [tgrosinger/recent-files-obsidian#58]
Obsidian 1.3.1
Default theme
macOS 13.3.1 (a)

The Recent Files list style is off, I guess Obsidian 1.3 changed the HTML/CSS again.

![CleanShot 2023-05-18 at 09 59 00@2x](https://github.com/tgrosinger/recent-files-obsidian/assets/1501/12bbe737-cdb4-47d4-ab41-402abc1e1b5c)

**Comment by swehba** [comment]
+1

**Comment by qibbo** [comment]
+1

**Comment by qibbo** [comment]
![image](https://github.com/tgrosinger/recent-files-obsidian/assets/20324306/4a5864d0-3ce8-4371-b022-2af87a0258cc)

**Comment by marconoris** [comment]
+1

**Comment by marconoris** [comment]
I have same issue but if you disable and enable plugin again, it works perfectly...

**Comment by czottmann** [comment]
> I have same issue but if you disable and enable plugin again, it works perfectly...

Oh, it works fine — just the styling is broken.

**Comment by tgrosinger** [comment]
Looks like we need to add the `tree-item`, `tree-item-self`, and `tree-item-inner` classes to fix the styling.

**Comment by czottmann** [comment]
Thanks, appreciate it!
