### ISSUE TITLE
keyboard friendly

### ISSUE THREAD

**Issue by manogna4** [tgrosinger/recent-files-obsidian#6]
can you add a feature to make the list accessible using only the keyboard?
it could be done using a modal similar to the quick switcher, but the modal only shows the recent 'x' files, and one types in filenames to filter from that list.

**Comment by tgrosinger** [comment]
Hi @manogna4,
The quick switcher (ctrl+d by default I think) by default shows the most recently opened files. I'm not sure it's worth reimplementing that for such a subtle difference.

Let me know if the existing quick switcher works for your needs.

**Comment by manogna4** [comment]
the quickswitcher shows only the last 9 used files. I can't find an option to configure that. 

Also you can't search only within only those 9 files since it searches the whole vault as you start typing.

As the vault grows, I think adding the ability to search only previous 'x' files (where x is a largish number like 30) will be very useful. 

Of course, it would be better as part of the quickswitcher itself, but the devs are busy with more important things and I think the recent files plug in might be a nice place to incorporate this feature too. I understand if you don't though...

**Comment by tgrosinger** [comment]
I see where you are coming from, but not quite sure yet. I am going to put this one on hold for now and think about what the user experience should be for this plugin. 

Thank you very much for the suggestion 🙂

**Comment by base-I** [comment]
You can move the plugin into a new pane; there is a plugin to cycle through open panes. That should at least be a bit of the functionality you want

**Comment by manogna4** [comment]
> You can move the plugin into a new pane; there is a plugin to cycle through open panes. That should at least be a bit of the functionality you want

I prefer it in the sidebar. That way when you click on a note from recent files, you don't lose the pane. Having a modal would allow one the functionality of searching **only** through the last x files using only the keyboard.

The quick switcher cannot configure x (it's set to 9), and it does not have the ability to search amongst them. You have to read through every single title until you find what you are looking for.

**Comment by tgrosinger** [comment]
I'm going to stick with my initial feelings that this is outside the scope of this plugin.
