### ISSUE TITLE
Note titles shift on hover using Obsidian v1.4+

### ISSUE THREAD

**Issue by trainbuffer** [tgrosinger/recent-files-obsidian#60]
Can't remember exactly when this started, (Obsidian v1.4+), but the note titles shift slightly on hover.

This CSS seems to sort it out, but not sure if this is the best approach.  

```css
.workspace-leaf-content[data-type="recent-files"] .tree-item-self {
    align-items: unset;
}
```

https://github.com/tgrosinger/recent-files-obsidian/assets/3751726/50225e08-1ad1-4b26-9f68-9bee7e573d4d

Thanks! 

---

macOS 13.5
Obsidian v1.4.3 Sandbox
Recent Files v1.3.7

```
SYSTEM INFO:
	Obsidian version: v1.4.3
	Installer version: v1.3.5
	Operating system: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 22.6.0
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Recent Files v1.3.7
```

**Comment by tgrosinger** [comment]
I am aware of this issue and have attempted to fix it, but haven't succeeded yet. PR definitely welcome!

**Comment by mkasu** [comment]
For me the CSS snippet above seems to work well. Thanks!

Should it be included in the plugin or are there some side-effects from it?
