### ISSUE TITLE
How "Open note in split" works

### ISSUE THREAD

**Issue by merlinuwe** [tgrosinger/recent-files-obsidian#63]
Thanks for your great plugin.

I cannot use Open note in split, even not when I restart Obsidian.

	Obsidian version: v1.4.14
	Installer version: v1.4.14
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.2.3
	Snippets enabled: 62
	Restricted mode: off

What can I do to open a note in split mode with your plugin?

**Comment by zuzic-filip** [comment]
I have the same problem.
Whatever I enter in "Open note in", the note is always opened in the same tab.

Obsidian version: v1.5.8
Installer version: v1.4.16
Operating system: Windows 10

**Comment by merlinuwe** [comment]
Yes, i can commit. 

	Obsidian version: v1.5.12
	Installer version: v1.5.12
	Operating system: Windows 10 Home 10.0.19045

![image](https://github.com/tgrosinger/recent-files-obsidian/assets/4138869/b2d5560b-51cb-49e1-964a-00d21d86ffa0)

**Comment by tgrosinger** [comment]
I have removed this setting because it was very confusing. It now uses the standard Obsidian behavior with "ctrl" for new tab and "ctrl + alt" for new tab group.
