### ISSUE TITLE
[enhancement] "last opened date/time" property

### ISSUE THREAD

**Issue by SuperCowProducts** [tgrosinger/recent-files-obsidian#66]
Like some plugins such as Templater offer a "last modified date" property, having a "last opened date" could be useful.

**Comment by nicolnt** [comment]
You mean making the plugin add and update a property in files?
Can you elaborate on your current issue and propose a use case to clarify your feature request please?

**Comment by tgrosinger** [comment]
I'm going to close this due to lack of details. Please feel free to reopen with additional context.
