### ISSUE TITLE
[Enhancement] Omit Bookmarked Files

### ISSUE THREAD

**Issue by therithwikrayani** [tgrosinger/recent-files-obsidian#67]
Is it possible to add a way to omit all the bookmarked files from the recent files list?
I always have the bookmarks list open, so having them show up in the recent files is redundant.

**Comment by tgrosinger** [comment]
Hello,
I think this would be a good feature to add. It would need a new boolean and checkbox added to the settings, and a filter added to `shouldAddFile`. Very similar to #87.
