### ISSUE TITLE
its icon appears at the top rather than in the sidebar

### ISSUE THREAD

**Issue by changxiaotian** [tgrosinger/recent-files-obsidian#80]
![image](https://github.com/tgrosinger/recent-files-obsidian/assets/152055436/3fe9d80e-766d-46d5-b9e5-928ac86715fd)
After installing the plugin, its icon appears at the top rather than in the sidebar, and I have to click the icon to see recent files, which is inconvenient. 
Does anyone know how to solve this problem?

**Comment by tgrosinger** [comment]
This plugin does not have a ribbon icon. Clicking that button will show the sidebar view. You can also click and drag it to move the view to other places in the sidebars.

**Comment by changxiaotian** [comment]
更口语化一点，可以改动我的原意

**Comment by changxiaotian** [comment]
Thanks for reminding me, my issue is sorted out now.
