### ISSUE TITLE
Support notes preview in the same side bar

### ISSUE THREAD

**Issue by samishchandra** [tgrosinger/recent-files-obsidian#84]
Can we add support for preview notes for the recent files in the same side panel. This is very useful feature and many apps do support this like Apple Notes, Bear, Typora, Mail etc.

**Comment by tgrosinger** [comment]
Obsidian has a core plugin called Page Preview. If you enable this plugin, then pressing ctrl while hovering over a note in the Recent Files view will show a preview.

Feel free to reopen if you have additional questions.
