### ISSUE TITLE
With Obsidian 1.7.2 + plugin ver 1.5.0, the app switches to the Recent Files view upon every launch

### ISSUE THREAD

**Issue by luckman212** [tgrosinger/recent-files-obsidian#86]
Mild annoyance: when launching Obsidian now (1.7.2) it always force-switches my navigator panel to the Recent Files view. I prefer to have the File tree as my default.

**Comment by tgrosinger** [comment]
Thanks for the report. Should be fixed in the latest release!

**Comment by luckman212** [comment]
Indeed, thanks for the super quick fix! 🙏
