### ISSUE TITLE
[Feature Request] Omitted frontmatter patterns

### ISSUE THREAD

**Issue by zayKenyon** [tgrosinger/recent-files-obsidian#87]
Hi! Love the plugin, thanks for all the continued work you put into it 😊.

I have a few scattered notes all linked together with the same tag which I wouldn't like displayed in the Recent Files pane. They are quite personal to me and I am worried that one day I will forget to close them before I go to a lecture 😅.

Similar to omitting files because of their path, is it possible to omit files based off their tags? If so, I would love to have a go at PR'ing this, being able to contribute to a plugin I use daily would be awesome! The way I imagine the user creating ignored tags would be the same one regex per line input in-order to maintain consistency throughout the plugin.

**Comment by tgrosinger** [comment]
Hello,
Yeah I think that would be possible and a nice feature to add.

You should be able to get the tags for a file using `app.MetadataCache.getFileCache(file).tags`. So I would recommend modifying `shouldAddFile` ([source](https://github.com/tgrosinger/recent-files-obsidian/blob/main/main.ts#L362-L375)) to also iterate the tags of that file and make sure none of them are configured to be omitted.

Let me know if you have any questions as you work on a PR. Thank you!
