### ISSUE TITLE
How can I pin the recent files icon on the pane?

### ISSUE THREAD

**Issue by jiangaq** [tgrosinger/recent-files-obsidian#88]
To avoid close "recent files" by clicking cmd+w carelessly:

1. How can I pin it on the pane?
2. If closed on the pane already, how can I let it appear on the pane again? I tried to disable and enable the plugin, but no appear.

**Comment by seren** [comment]
I’m not sure if you can pin it, but you can reopen it by opening the command pallet and selecting “Recent Files: Open”.

**Comment by tgrosinger** [comment]
This view cannot be pinned when it's in the center column of Obsidian with notes, however I would suggest moving it into either the left or right sidebar. When it's in the sidebar it will not be closed with `cmd+w`.

Here's some more information about the sidebars: https://help.obsidian.md/User+interface/Sidebar
