### ISSUE TITLE
[FR] Option to show file types (e.g. canvas)

### ISSUE THREAD

**Issue by albertoloscerritos** [tgrosinger/recent-files-obsidian#92]
Hi, thanks for the great plugin. One option I think would be very useful is the option to show the file type for files that are not .mc e.g. canvas files. I use canvas a lot, and tend to have multiple files, md and canvas, with the same name. In the explorer I can easily see the difference:
![image](https://github.com/user-attachments/assets/ea655910-0761-45ac-bc5a-d388d0ce4fe4)
But not in the plugin:
![image](https://github.com/user-attachments/assets/7a2861b5-482c-49b9-be85-22fb616e7e6c)
Thanks for reading :)

**Comment by tgrosinger** [comment]
Closed with ddbae59.
